/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロジェクトの一覧を見る
         * @description 登録済みのプロジェクトを、カテゴリの表示順 → カテゴリ内でのプロジェクトの表示順で返す
         *     登録が1件もない場合は、空の一覧を返す（エラーにはならない）
         */
        get: operations["GetAllProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 車輪の再発明として取り組むプロジェクト（自作 ls コマンド、JSONパーサなど） */
        Project: {
            /**
             * @description プロジェクトを一意に識別するID
             *     例: cli-ls
             */
            id: string;
            /**
             * @description 所属するカテゴリのID
             *     例: cli
             */
            categoryId: string;
            /**
             * @description プロジェクトの名前
             *     例: 自作 ls コマンド
             */
            title: string;
            /**
             * Format: int32
             * @description 難易度
             *     1〜3の整数（1が易しい、3が難しい）
             *     null は「未設定」を意味する
             */
            difficulty: null | number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAllProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
}
